language: java
jdk:
  - oraclejdk8
before_install:
  - git submodule update --init
  - ./remap.sh
  - ./decompile.sh
  - ./init.sh
  - ./newApplyPatches.sh
after_success:
  - ./paperclip.sh
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work'
